### PR TITLE
Angular SDK: Update to Angular 13

### PR DESCRIPTION
**Pull request by egilkh**

### CODE REVIEW

**Comment by egilkh** [comment]
Please note that Angular now requires Node >12, so running the tests on 10 should fail.

**Comment by egilkh** [comment]
And it seems that bails 12 and 14 from running :(

Here is the output from my run locally

```~/projects/transifex-javascript/packages/angular (update-to-angular-13 $)$ ng build
Building Angular Package

------------------------------------------------------------------------------
Building entry point '@transifex/angular'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy partial compilation mode.
✔ Generating FESM2020
✔ Generating FESM2015
✔ Copying assets
ℹ Removing devDependencies section in package.json.
✔ Writing package manifest
✔ Built @transifex/angular

------------------------------------------------------------------------------
Built Angular Package
 - from: /Users/egilkh/projects/transifex-javascript/packages/angular/projects/tx-native-angular-sdk
 - to:   /Users/egilkh/projects/transifex-javascript/packages/angular/dist/tx-native-angular-sdk
------------------------------------------------------------------------------

Build at: 2021-11-22T06:46:41.220Z - Time: 4913ms
```

**Comment by egilkh** [comment]
I can change the tests, but I do not have any experience with the other libs. Do they still require Node 10?

**Comment by egilkh** [comment]
I'm actually unsure if it will work, it still provides the FESM2015 module I see in the output. So I think it would work. But if you put it in the 2 branch and mark it backwards incompatible. 

Have to admit I've not maintained a Angular library myself so I don't have a 11 and 12 test version up and running. Do you guys have those test environments.

This is what the compiler says when building:

```Building Angular Package

------------------------------------------------------------------------------
Building entry point '@transifex/angular'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy partial compilation mode.
✔ Writing FESM bundles
✔ Copying assets
ℹ Removing devDependencies section in package.json.
✔ Writing package manifest
✔ Built @transifex/angular

------------------------------------------------------------------------------
Built Angular Package
 - from: /Users/egilkh/projects/transifex-javascript/packages/angular/projects/tx-native-angular-sdk
 - to:   /Users/egilkh/projects/transifex-javascript/packages/angular/dist/tx-native-angular-sdk
------------------------------------------------------------------------------

Build at: 2021-11-22T14:07:13.349Z - Time: 3693ms
```

It creates FESM2015, FESM2020 and ESM2020 folder, I assume those will be backward compatible as no changes is done to the usage of angular. So no Angular/Component changes.

**Comment by egilkh** [comment]
Seems jasmine can't be run on node 16, so we are in a bit of a pickle.

**Comment by pablotransifex** [comment]
@egilkh I did a test with @nbasili and determined that the problem is the `peerDependencies` in the nested (package source) `package.json` file. Can you upgrade there also the dependencies to:

`"peerDependencies": {
    "@angular/common": "^13.0.2",
    "@angular/core": "^13.0.2",
    "@transifex/native": "^1.0.5"
  },`

and let us know if everything is ok?

**Comment by egilkh** [comment]
I can run the tests fine if I do it in the angular folder, but when run via Lerna I get this error. Looking into it

**Comment by pablotransifex** [comment]
> I can run the tests fine if I do it in the angular folder, but when run via Lerna I get this error. Looking into it

I noticed that the package is built, but the tests are failing in github due to that strange error with the `Tesbed.inject()`
We did run the lerna bootstrap locally and everything went well, don't know why in github flow is not working.

**Comment by egilkh** [comment]
So. Figured out after checking package.json in the library folder. Which should not have anything but peerDependencies that it has some dependencies. Which in turn put in node_modules there and everything got confused :)

I just removed the dependencies there. Not sure where they came from (probably me at some point). But they are not needed and it works without them as it should.

Now we are cooking :)

**Comment by pablotransifex** [comment]
> So. Figured out after checking package.json in the library folder. Which should not have anything but peerDependencies that it has some dependencies. Which in turn put in node_modules there and everything got confused :)
> 
> I just removed the dependencies there. Not sure where they came from (probably me at some point). But they are not needed and it works without them as it should.
> 
> Now we are cooking :)

Great!

**Comment by egilkh** [comment]
Squashed it to one commit on master.

**Comment by egilkh** [comment]
@pablotransifex Should I change it to the 2.x.x branch?

**Comment by pablotransifex** [comment]
> @pablotransifex Should I change it to the 2.x.x branch?

@egilkh Better in 2.x as we are keeping the Angular v11 in the 1.x version. I will test later on your PR on a sample app and then approve. The tests in v2 are not set up yet, but in the next days will be ok so we can use the new version for this major upgrade. 
FYI @nbasili

**Comment by egilkh** [comment]
As there is no tests here, this is the last run : https://github.com/transifex/transifex-javascript/actions/runs/1494718748

**Pull request merged**
