### PR TITLE
feat(chore): Angular 16 update

### PR DESCRIPTION
**Pull request by tse018**
Updatet to Angular 16, had some issues with running tests and therefor resulted in why I added new ts.config.json file on tests folder, now all the tests is runned on Angular v16. 

Added .github/workflows/angular-versions.yaml, so application can be runned on angular version 14, 15 and 16 based on what angular version want to use. Not sure if it is correct way, let me know if it need to be modified / improved.

### CODE REVIEW

**Comment by pablotransifex** [comment]
@tse018 The test/build for node 14 is failing:

`The Angular CLI requires a minimum of v16.13.`

**Comment by tse018** [comment]
> @tse018 The test/build for node 14 is failing:
> 
> `The Angular CLI requires a minimum of v16.13.`

Angular 16 doesn´t support node v14

**Comment by pablotransifex** [comment]
> > @tse018 The test/build for node 14 is failing:
> > `The Angular CLI requires a minimum of v16.13.`
> 
> Angular 16 doesn´t support node v14

Node versions updated to 16,18, 20. Could you please rebase to check if tests are working fine?

**Comment by tse018** [comment]
> @tse018 Node versions updated to 16,18, 20. Could you please rebase to check if tests are working fine?

Yes

**Comment by tse018** [comment]
@pablotransifex Let me know when you are ready to merge this, thanks. 
Need it for angular 16 project.

**Comment by pablotransifex** [comment]
> @pablotransifex Let me know when you are ready to merge this, thanks. Need it for angular 16 project.

I checked the PR on an Angular 16 project of mine and worked fine, just we need a rebase to merge your PR. @tse018

**Comment by tse018** [comment]
Have resolved the merge conflicts to using the newest transifex versions

**Comment by pablotransifex** [comment]
> Have resolved the merge conflicts to using the newest transifex versions

Thank you @tse018 now we need to fix the tests, it seems to be dependencies conflicts.

**Comment by tse018** [comment]
> > Have resolved the merge conflicts to using the newest transifex versions
> 
> Thank you @tse018 now we need to fix the tests, it seems to be dependencies conflicts.

 lerna ERR! npm run test stderr:

Error: Cannot find module 'http'

do you know which dependencies its missing from?

**Comment by pablotransifex** [comment]
@tse018 We will try to find out, in the meantime, maybe it's related to the angular-versions.yaml? We are running tests for node 16, 18 and 20, inside that file there are other node versions, maybe we can test without this file at all or fix those versions inside?

**Comment by pablotransifex** [comment]
@tse018 We merge a fix for `nock` https://github.com/transifex/transifex-javascript/pull/217 so please rebase again, and probably we don't need the angular workflow file, as we are using node version >= 16.

We are thinking on a version for angular 16 only, so maybe better remove the peer dependencies for 14 and 15 and the mentioned angular workflow file.

For older angular versions, users can use other TX Native version that supports them.

**Comment by tse018** [comment]
> @tse018 We merge a fix for `nock` #217 so please rebase again, and probably we don't need the angular workflow file, as we are using node version >= 16.
> 
> We are thinking on a version for angular 16 only, so maybe better remove the peer dependencies for 14 and 15 and the mentioned angular workflow file.
> 
> For older angular versions, users can use other TX Native version that supports them.

Understood, will remove and fix it now

**Review by pablotransifex — APPROVED** [review]
Nice work  @tse018, it was a bit of trouble with this, but in the end all good!

**Pull request merged**
