### PR TITLE
Angular SDK: make decorator params optional

### PR DESCRIPTION
**Pull request by egilkh**

### CODE REVIEW

**Comment by egilkh** [comment]
Having to put in {) for whenever there is not extra params is a bit aannoying 😄

**Comment by pablotransifex** [comment]
@egilkh This is the last one!

**Comment by egilkh** [comment]
@pablotransifex Aaah yeah :D

**Review by pablotransifex — APPROVED** [review]
LGTM

**Comment by pablotransifex** [comment]
@egilkh Great work man, you put some extra value to this SDK and now is more solid! Soon we'll release a new version!

**Comment by egilkh** [comment]
<3

**Pull request merged**
