### PR TITLE
Angular SDK: Add TranslatePipe

### PR DESCRIPTION
**Pull request by egilkh**

### CODE REVIEW

**Comment by egilkh** [comment]
I walked right into that one! Forgot the lint :( I'll fix.

**Comment by egilkh** [comment]
Please do note, as a measure to get key from the .html templates I had to use Function to parse the string that would be passed to the pipe and I disabled that line from ESLint. 

Is not ideal. On the other hand: Running the push command on templates that contain code is not something one should do and would require someone to not know the templates they were running the command on. Which might happen, but I do not think it's likely for most projects where only a select few people should be able to use the tokens/secrets.

**Review by pablotransifex — COMMENTED** [review]
Hello @egilkh we should add the export to the **public-api.ts** as follows:
```
/*
 * Public API Surface of tx-native-angular-sdk
 */

export * from './lib/interfaces';
export * from './lib/T.decorator';
export * from './lib/safe-html.pipe';
export * from './lib/translate.pipe';
export * from './lib/translation.service';
export * from './lib/T.component';
export * from './lib/UT.component';
export * from './lib/language-picker.component';
export * from './lib/TXNative.module';
```

in order to build the library, I got error if not present.

Another question is, did you try this pipe on a real project? If so, please let me know how you managed to be recognized in the HTML template, because I couldn't make it work.

Thank you in advance!

**Comment by egilkh** [comment]
Hey @pablotransifex 

Good catch there. I will change that. 

I did try in a real project, and I was able to find it. And use it.

On the other hand I do include the TxNativeModule in lazy-loaded modules where I want to use it. As just including TxNativeModule.forRoot() will not provide translate pipe or component to lazy loaded modules / components that is not declared by the AppModule. 

Full disclosure: I do have a module called TranslateModule already that is included everywhere, and I include TxNativeModule and export it again so all the old modules/components get access to TComponent, UTComponent, translate. Which is the same effect as including TxNativeModule in the Modules :)

This is the way we have organised our entire app.

**Comment by egilkh** [comment]
I'll do some more tests and make the changes needed :)

**Comment by egilkh** [comment]
Added the export to `public-api.ts`. I have no trouble using the translate pipe.

And running `npm run build` in the top level (lerna) gives this : 

```
$ npm run build

> root@ build /Users/egilkh/projects/transifex-javascript
> lerna run build

lerna notice cli v3.22.1
lerna info Executing command in 3 packages: "npm run build"
lerna info run Ran npm script 'build' in '@transifex/native' in 4.7s:

> @transifex/native@0.13.1 build /Users/egilkh/projects/transifex-javascript/packages/native
> NODE_ENV=production webpack --config ./webpack.config.js && cp src/index.d.ts dist/node.native.d.ts

Hash: 46830162ef80693579776df5dc358ba104dd3476
Version: webpack 4.46.0
Child
    Hash: 46830162ef8069357977
    Time: 3185ms
    Built at: 07/14/2021 11:15:58 AM
                 Asset     Size  Chunks                   Chunk Names
        node.native.js  140 KiB       0  [emitted]        main
    node.native.js.map  466 KiB       0  [emitted] [dev]  main
    Entrypoint main = node.native.js node.native.js.map
    [10] external "http" 42 bytes {0} [built]
    [11] external "https" 42 bytes {0} [built]
    [13] external "url" 42 bytes {0} [built]
    [34] external "stream" 42 bytes {0} [built]
    [35] external "assert" 42 bytes {0} [built]
    [41] external "tty" 42 bytes {0} [built]
    [42] external "util" 42 bytes {0} [built]
    [44] external "os" 42 bytes {0} [built]
    [46] external "zlib" 42 bytes {0} [built]
    [67] ./src/index.js + 9 modules 19.1 KiB {0} [built]
         | ./src/index.js 786 bytes [built]
         | ./src/policies/SourceErrorPolicy.js 297 bytes [built]
         | ./src/policies/SourceStringPolicy.js 265 bytes [built]
         | ./src/renderers/MessageFormatRenderer.js 369 bytes [built]
         | ./src/utils.js 4.95 KiB [built]
         | ./src/events.js 1.09 KiB [built]
         | ./src/TxNative.js 8.32 KiB [built]
         | ./src/policies/PseudoTranslationPolicy.js 1.41 KiB [built]
         | ./src/policies/ThrowErrorPolicy.js 321 bytes [built]
         | ./src/cache/MemoryCache.js 1.36 KiB [built]
        + 58 hidden modules
Child
    Hash: 6df5dc358ba104dd3476
    Time: 2745ms
    Built at: 07/14/2021 11:15:58 AM
                    Asset     Size  Chunks                   Chunk Names
        browser.native.js  122 KiB       0  [emitted]        main
    browser.native.js.map  498 KiB       0  [emitted] [dev]  main
    Entrypoint main = browser.native.js browser.native.js.map
    [43] (webpack)/buildin/global.js 472 bytes {0} [built]
    [49] ./src/index.js + 9 modules 29 KiB {0} [built]
         | ./src/index.js 766 bytes [built]
         | ./src/policies/SourceErrorPolicy.js 682 bytes [built]
         | ./src/policies/SourceStringPolicy.js 655 bytes [built]
         | ./src/renderers/MessageFormatRenderer.js 771 bytes [built]
         | ./src/utils.js 5.75 KiB [built]
         | ./src/events.js 1.08 KiB [built]
         | ./src/TxNative.js 14.9 KiB [built]
         | ./src/policies/PseudoTranslationPolicy.js 1.8 KiB [built]
         | ./src/policies/ThrowErrorPolicy.js 713 bytes [built]
         | ./src/cache/MemoryCache.js 1.94 KiB [built]
        + 48 hidden modules
lerna info run Ran npm script 'build' in '@transifex/react' in 2.8s:

> @transifex/react@0.13.1 build /Users/egilkh/projects/transifex-javascript/packages/react
> NODE_ENV=production microbundle-crl --no-compress --format modern,cjs && cp src/index.d.ts dist/index.d.ts && cp src/index.d.ts dist/index.modern.d.ts

Build "react" to dist:
       1336 B: index.js.gz
       1188 B: index.js.br
       1250 B: index.modern.js.gz
       1092 B: index.modern.js.br
lerna info run Ran npm script 'build' in '@transifex/angular-projects' in 8.9s:

> @transifex/angular-projects@0.13.1 build /Users/egilkh/projects/transifex-javascript/packages/angular
> ng build --prod

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@transifex/angular'
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Built Angular Package
 - from: /Users/egilkh/projects/transifex-javascript/packages/angular/projects/tx-native-angular-sdk
 - to:   /Users/egilkh/projects/transifex-javascript/packages/angular/dist/tx-native-angular-sdk
------------------------------------------------------------------------------
lerna success run Ran npm script 'build' in 3 packages in 13.6s:
lerna success - @transifex/angular-projects
lerna success - @transifex/native
lerna success - @transifex/react
```

**Comment by pablotransifex** [comment]
Hello @egilkh I did a TranslateModule and included in the AppModule like this:

```
import { NgModule } from '@angular/core';
import { TxNativeModule } from '@transifex/angular';

@NgModule({
  imports: [
    TxNativeModule.forRoot(),
  ],
  exports: [
    TxNativeModule,
  ]
})
export class TranslateModule { }
```

and in AppModule:

```
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';
import { LoginComponent } from './login/login.component';
import { PrivacyComponent } from './privacy/privacy.component';
import { TermsComponent } from './terms/terms.component';
import { TranslateModule } from './translate.module';

@NgModule({
  declarations: [
    AppComponent,
    LoginComponent,
    TermsComponent,
    HomeComponent,
    PrivacyComponent,
  ],
  imports: [
    AppRoutingModule,
    BrowserModule,
    ReactiveFormsModule,
    TranslateModule,
  ],
  providers: [
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

but still the pipe is not being recognised, the example I'm using is the angular project in our TX Native SDK sandbox, if you want to give a try on it: https://github.com/transifex/transifex-native-sandbox, probably I'm missing something.

**Comment by egilkh** [comment]
Hei there,

So I created my local "angular" install by doing `npm run build`: 

```
transifex-javascript/packages/angular (angular-sdk-translate-pipe)$ npm run build

> @transifex/angular-projects@0.13.1 build /Users/egilkh/projects/transifex-javascript/packages/angular
> ng build --prod

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@transifex/angular'
------------------------------------------------------------------------------
✔ Compiling TypeScript sources through NGC
✔ Bundling to FESM2015
✔ Bundling to UMD
✔ Minifying UMD bundle
ℹ Removing devDependencies section in package.json.
✔ Writing package metadata
ℹ Built @transifex/angular

------------------------------------------------------------------------------
Built Angular Package
 - from: /Users/egilkh/projects/transifex-javascript/packages/angular/projects/tx-native-angular-sdk
 - to:   /Users/egilkh/projects/transifex-javascript/packages/angular/dist/tx-native-angular-sdk
------------------------------------------------------------------------------
```

Then I cloned the https://github.com/transifex/transifex-native-sandbox and did a `npm i` inside the angular folder. Now I needed to swap out the installed one with my local one, I just deleted @transifex/angular and did `ln -s  /Users/egilkh/projects/transifex-javascript/packages/angular/dist/tx-native-angular-sdk angular` to get in to be @transifex/angular. A sneaky "install" of the lib, probably npm link or something would be better. But this serves my purpose.

I booted up Angular with a `ng serve` in the angular folder. 

I added `{{ 'I am the king' | translate }}` inside terms.component.html, with no error, and ng server does not complain. Proof that the AppModule with it's TxNativeModule import provides the pipe. I'll attach a screen shot from my VS.Code.

image

Which means TxNativeModule works. With or without a module import / exporting it you should be able to use it directly in any component within AppModule if it is provided there. And one should provide it there to ensure TranslationService is provided to all the uses one can have.

Would you like me to expand and create a proxy TranslationModule with the same test?

**Comment by egilkh** [comment]
As a note, if I create translate.module.ts with the contents of your TranslateModule. And remove TxNativeModule from AppModule I do indeed get errors, until I import TranslateModule and the errors go away.

**Comment by egilkh** [comment]
@pablotransifex I forgot to tag you (and therefor bothering you) :)

**Comment by pablotransifex** [comment]
> @pablotransifex I forgot to tag you (and therefor bothering you) :)

No problem, I did the same, but my problem is that the page is rendering the code not the result of the pipe, see what I can see in my screen:

image

I think the problem is when there are HTML tags embedded in the string before the pipe, try with:

```
{{ 'Hello there! <em>test</em>' | translate }}
```

Maybe we need to sanitize first the string, and then pass it to the translate pipe.

@egilkh

**Comment by egilkh** [comment]
@pablotransifex 

I do not think Angular allows HTML inside the string there. Which is why it bails and just prints it out. Which makes sense and one should not use HTML inside {{ }}, we have HTML (the template) for that and the T/UT component. Right?

I'd say it's doing correct now. 

Which is the same if you use the DatePipe as well, Angular just bails. 

I've never used a pipe with HTML input and with T/UT (the correct one) we are covered. The pipe is nice for things like [matTooltip]="'Login' | translate" or simple strings {{ 'There are no hunters' | translate }}. 

Most usage should be with T/UT, agreed?

**Comment by pablotransifex** [comment]
> @pablotransifex
> 
> I do not think Angular allows HTML inside the string there. Which is why it bails and just prints it out. Which makes sense and one should not use HTML inside {{ }}, we have HTML (the template) for that and the T/UT component. Right?
> 
> I'd say it's doing correct now.
> 
> Which is the same if you use the DatePipe as well, Angular just bails.
> 
> I've never used a pipe with HTML input and with T/UT (the correct one) we are covered. The pipe is nice for things like [matTooltip]="'Login' | translate" or simple strings {{ 'There are no hunters' | translate }}.
> 
> Most usage should be with T/UT, agreed?

You're right, the correct approach could be this for using HTML:

```
<span [outerHTML]="'Hello there! <em>test</em>' | translate"></span>
```

So let's say that we are ok, and the pipe is working as expected :) @egilkh

**Comment by egilkh** [comment]
Sweet! @pablotransifex 

I just made a stupidPipe, and when it bails it never even runs the Pipe (as expected). Just so we know and tested :)

> You're right, the correct approach could be this for using HTML (worked for me):
> 
> ```
> <span [outerHTML]="'Hello there! <em>test</em>' | translate"></span>
> ```
> 
> So let's say that we are ok, and the pipe is working as expected :) @egilkh

At that point I think one should use T/UT, but to each their own I guess :)

**Review by pablotransifex — APPROVED** [review]
LGTM, the pipe was on our mind from the beginning, but we decided to postpone it, with your code this is a reality, great work @egilkh!

**Comment by egilkh** [comment]
@pablotransifex Thank you for the kind words and the help :)

**Pull request merged**
